[package]
name = "quadtree"
version = "0.1.0"
# edition = "2024" # 2024 is not yet stable, using it can lead to unexpected behavior
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
dirs = "4.0" # To get the user's home directory
