[package]
name = "yml_io"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "4.0"
ndarray = { version = "=0.15" }
ndarray-npy = { version = "=0.8" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
